# Generated by Django 6.1.1 on 2026-10-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.PositiveIntegerField(editable=False, unique=True)),
                ('date', models.DateField()),
                ('received_from', models.CharField(db_index=True, max_length=150, verbose_name='Received with thanks from M/s.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_in_words', models.CharField(editable=False, max_length=255)),
                ('towards', models.CharField(help_text='e.g. MBA Finance', max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('gpay', 'GPay / UPI'), ('cheque', 'Cheque'), ('bank', 'Bank transfer')], default='cash', max_length=10)),
                ('cashier', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-receipt_no'],
            },
        ),
    ]
